-- MySQL / MariaDB schema for the PHP CRM
CREATE TABLE companies (
  id VARCHAR(24) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  website VARCHAR(255), industry VARCHAR(120), phone VARCHAR(60), city VARCHAR(120),
  notes TEXT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE contacts (
  id VARCHAR(24) PRIMARY KEY,
  first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120),
  email VARCHAR(255), phone VARCHAR(60), job_title VARCHAR(160),
  company_id VARCHAR(24) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'lead',
  source VARCHAR(60), notes TEXT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE deals (
  id VARCHAR(24) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  company_id VARCHAR(24) NULL, contact_id VARCHAR(24) NULL,
  stage VARCHAR(20) NOT NULL DEFAULT 'New',
  amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  `close` DATE NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE activities (
  id VARCHAR(24) PRIMARY KEY,
  type VARCHAR(20) NOT NULL DEFAULT 'task',
  subject VARCHAR(255) NOT NULL,
  contact_id VARCHAR(24) NULL, deal_id VARCHAR(24) NULL,
  due DATE NULL, description TEXT,
  done TINYINT(1) NOT NULL DEFAULT 0,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
